# Generated by Django 5.0 on 2023-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
