# Generated by Django 5.0 on 2023-12-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_private_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='is_an_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
