# Generated by Django 5.0 on 2023-12-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_roominvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominvitation',
            name='is_accepted',
        ),
    ]
