# Generated by Django 5.0 on 2024-01-02 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_message_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users_banned',
            field=models.ManyToManyField(related_name='banned_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
