# Generated by Django 5.0 on 2024-01-02 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_alter_room_users_banned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users_banned',
            field=models.ManyToManyField(related_name='banned_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
